### ISSUE TITLE
@Team Discutions!!

### ISSUE THREAD

**Issue by MateiGamingYTB** [ILOVEMCPE/ILOVEMCPEServers#6]

**Comment by MateiGamingYTB** [comment]
Welcome @ImagicalGamer on this Team!

**Comment by ImagicalGamer** [comment]
Hey.

**Comment by MateiGamingYTB** [comment]
Welcome to this Resposity

**Comment by ImagicalGamer** [comment]
Thanks, what's the latest project? Or something to start on?

**Comment by MateiGamingYTB** [comment]
we do a server plugins

**Comment by MateiGamingYTB** [comment]
a ready-made pocketmine server

**Comment by ImagicalGamer** [comment]
Ok.

**Comment by MateiGamingYTB** [comment]
you have skype or facebook?

**Comment by MateiGamingYTB** [comment]
man you add/update your SG plugin
ok?

**Comment by ImagicalGamer** [comment]
Neither, I will update the plug though.

**Comment by MateiGamingYTB** [comment]
ok

**Comment by TheKillerTacos** [comment]
So. now Im back to make my own server, so, Im somehow Busy, and cant check all the plugins included in here, so if someone Could make a list.md within /plugins folder to know everyplugin name and a little description

**Comment by KairusDarkSeeker** [comment]
@MateiGamingYTB why are you copying my profile picture on both github and YouTube

**Comment by MateiGamingYTB** [comment]
Who want to Mark this reposity in ABANDONATED? I don't want but not help anyone with nothing.......
